version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9008:9000"
    volumes:
      - ./data/sonarqube_data:/data/opt/sonarqube/data
      - ./data/sonarqube_logs:/data/opt/sonarqube/logs
      - ./data/sonarqube_extensions:/data/opt/sonarqube/extensions
    networks:
      - broker-restaurante

  postgres:
    image: postgres:15
    container_name: restaurantedb
    networks:
      - broker-restaurante
    environment:
      POSTGRES_DB: restaurante
      POSTGRES_USER: restauranteusr
      POSTGRES_PASSWORD: Restaurante2025@sistema
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


networks:
  broker-restaurante:
    driver: bridge
