server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
sonar:
  token: sqp_e6b0eaa38d92c4c69bb9e554ef98feceba932e9c
  host:
    url: http://localhost:9008
  projectKey: restaurante
  projectName: restaurante
  projectVersion: 1.0
  sources: src/main/java
  tests: src/test/java
  jacoco:
    reportPath: target/jacoco.exec

tolerancia-mesa: ${TOLERANCIA_MESA:2}